version: '3.7'

services:
  app:
    build:
      context: ../
      dockerfile: dev_tools/Dockerfile
    image: dropcoin-main
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ../:/app
    env_file: .env.dev
  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=dropcoin
      - POSTGRES_PASSWORD=dropcoin
      - POSTGRES_DB=dropcoin
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: